#!/usr/bin/with-contenv bash

umask 022

PATH=/usr/bin:/usr/local/bin:$PATH

echo "Starting Sonarr"
exec s6-setuidgid bytesized /usr/bin/mono /opt/NzbDrone/NzbDrone.exe -data=/config -nobrowser
echo "Sonarr shut down"
